name: Salesforce CI/CD (Github)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: docker://salesforce/salesforcedx:latest-full
      options: --user root
    environment: 
      name: develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Github Actor- ${{ github.actor }}"
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # fetch depth is set to 0 to get all commit numbers
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global --add safe.directory /__w/sf-cicd-github/sf-cicd-github
          git config --global user.email "paul-tuura@slalom.com"
          git config --global user.name "Paul"

      - name: Check SFDX, Node versions
        run: |
          npm i shelljs
          sfdx --version
          node --version

      # Runs a set of commands using the runners shell
      - name: Run script
        run: node ./deployments/deploy.js --authUrl=${{ secrets.SFDC_AUTH_URL }} --branch=develop --buildId=01 --snapshotBranch=${{ vars.ORG_SNAPSHOT_BRANCH }} --testLevel=${{ vars.TEST_LEVEL }} --checkDeploy=${{ vars.CHECK_DEPLOY }}